[package]
name = "zip-merge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.95" }
clap = { version = "4.5.29", features = ["derive"] }
env_logger = { version = "0.11.6" }
log = { version = "0.4.25" }
zip = { version = "2.2.2" }